---
name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pack Build
        uses: dfreilich/pack-action@v2.1.1
        with:
          args: 'build garethjevans/simple-conventions:latest --builder paketobuildpacks/builder:full --publish'
